from test.base_test import BaseTest


class TestAudioEffectsUpdateBass(BaseTest):
    def setUp(self):
        super().setUp()

    def test_update_default_bass(self):
        self.audio_effects.update_bass(0)
        actual = self.audio_effects.get_config()
        expected = {
            "output": {
                "blocklist": ["Virtual Surround Sink Stream from VirtualSurround"],
                "equalizer#0": {
                    "balance": -2.7755575615628914e-17,
                    "bypass": False,
                    "input-gain": 0.0,
                    "left": {
                        "band0": {
                            "frequency": 120.0,
                            "gain": 0,
                            "mode": "BWC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band1": {
                            "frequency": 140.0,
                            "gain": 0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band2": {
                            "frequency": 200.0,
                            "gain": 0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band3": {
                            "frequency": 250.0,
                            "gain": 0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band4": {
                            "frequency": 1000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band5": {
                            "frequency": 2000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band6": {
                            "frequency": 5000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band7": {
                            "frequency": 8000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                    },
                    "mode": "IIR",
                    "num-bands": 32,
                    "output-gain": 0.0,
                    "pitch-left": 0.0,
                    "pitch-right": 0.0,
                    "right": {
                        "band0": {
                            "frequency": 120.0,
                            "gain": 0,
                            "mode": "BWC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band1": {
                            "frequency": 140.0,
                            "gain": 0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band2": {
                            "frequency": 200.0,
                            "gain": 0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band3": {
                            "frequency": 250.0,
                            "gain": 0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band4": {
                            "frequency": 1000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band5": {
                            "frequency": 2000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band6": {
                            "frequency": 5000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band7": {
                            "frequency": 8000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                    },
                    "split-channels": False,
                },
                "plugins_order": ["equalizer#0"],
            }
        }

        self.assertEqual(actual, expected)

    def test_update_bass_steps(self):
        self.audio_effects.update_bass(3)
        actual = self.audio_effects.get_config()
        expected = {
            "output": {
                "blocklist": ["Virtual Surround Sink Stream from VirtualSurround"],
                "equalizer#0": {
                    "balance": -2.7755575615628914e-17,
                    "bypass": False,
                    "input-gain": 0.0,
                    "left": {
                        "band0": {
                            "frequency": 120.0,
                            "gain": 4,
                            "mode": "BWC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band1": {
                            "frequency": 140.0,
                            "gain": 6,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band2": {
                            "frequency": 200.0,
                            "gain": 6,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band3": {
                            "frequency": 250.0,
                            "gain": 6,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band4": {
                            "frequency": 1000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band5": {
                            "frequency": 2000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band6": {
                            "frequency": 5000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band7": {
                            "frequency": 8000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                    },
                    "mode": "IIR",
                    "num-bands": 32,
                    "output-gain": 0.0,
                    "pitch-left": 0.0,
                    "pitch-right": 0.0,
                    "right": {
                        "band0": {
                            "frequency": 120.0,
                            "gain": 4,
                            "mode": "BWC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band1": {
                            "frequency": 140.0,
                            "gain": 6,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band2": {
                            "frequency": 200.0,
                            "gain": 6,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band3": {
                            "frequency": 250.0,
                            "gain": 6,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band4": {
                            "frequency": 1000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band5": {
                            "frequency": 2000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band6": {
                            "frequency": 5000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band7": {
                            "frequency": 8000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                    },
                    "split-channels": False,
                },
                "plugins_order": ["equalizer#0"],
            }
        }

        self.assertEqual(actual, expected)

        self.audio_effects.update_bass(-2)
        actual = self.audio_effects.get_config()
        expected = {
            "output": {
                "blocklist": ["Virtual Surround Sink Stream from VirtualSurround"],
                "equalizer#0": {
                    "balance": -2.7755575615628914e-17,
                    "bypass": False,
                    "input-gain": 0.0,
                    "left": {
                        "band0": {
                            "frequency": 120.0,
                            "gain": -2,
                            "mode": "BWC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band1": {
                            "frequency": 140.0,
                            "gain": -2,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band2": {
                            "frequency": 200.0,
                            "gain": -2,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band3": {
                            "frequency": 250.0,
                            "gain": -2,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band4": {
                            "frequency": 1000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band5": {
                            "frequency": 2000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band6": {
                            "frequency": 5000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band7": {
                            "frequency": 8000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                    },
                    "mode": "IIR",
                    "num-bands": 32,
                    "output-gain": 0.0,
                    "pitch-left": 0.0,
                    "pitch-right": 0.0,
                    "right": {
                        "band0": {
                            "frequency": 120.0,
                            "gain": -2,
                            "mode": "BWC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band1": {
                            "frequency": 140.0,
                            "gain": -2,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band2": {
                            "frequency": 200.0,
                            "gain": -2,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band3": {
                            "frequency": 250.0,
                            "gain": -2,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band4": {
                            "frequency": 1000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band5": {
                            "frequency": 2000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band6": {
                            "frequency": 5000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band7": {
                            "frequency": 8000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                    },
                    "split-channels": False,
                },
                "plugins_order": ["equalizer#0"],
            }
        }

        self.assertEqual(actual, expected)


class TestAudioEffectsUpdateTreble(BaseTest):
    def setUp(self):
        super().setUp()

    def test_update_default_treble(self):
        self.audio_effects.update_treble(0)
        actual = self.audio_effects.get_config()
        expected = {
            "output": {
                "blocklist": ["Virtual Surround Sink Stream from VirtualSurround"],
                "equalizer#0": {
                    "balance": -2.7755575615628914e-17,
                    "bypass": False,
                    "input-gain": 0.0,
                    "left": {
                        "band0": {
                            "frequency": 120.0,
                            "gain": 0,
                            "mode": "BWC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band1": {
                            "frequency": 140.0,
                            "gain": 0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band2": {
                            "frequency": 200.0,
                            "gain": 0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band3": {
                            "frequency": 250.0,
                            "gain": 0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band4": {
                            "frequency": 1000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band5": {
                            "frequency": 2000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band6": {
                            "frequency": 5000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band7": {
                            "frequency": 8000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                    },
                    "mode": "IIR",
                    "num-bands": 32,
                    "output-gain": 0.0,
                    "pitch-left": 0.0,
                    "pitch-right": 0.0,
                    "right": {
                        "band0": {
                            "frequency": 120.0,
                            "gain": 0.0,
                            "mode": "BWC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band1": {
                            "frequency": 140.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band2": {
                            "frequency": 200.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band3": {
                            "frequency": 250.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band4": {
                            "frequency": 1000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band5": {
                            "frequency": 2000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band6": {
                            "frequency": 5000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band7": {
                            "frequency": 8000.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                    },
                    "split-channels": False,
                },
                "plugins_order": ["equalizer#0"],
            }
        }

        self.assertEqual(actual, expected)

    def test_update_treble_steps(self):
        self.audio_effects.update_treble(3)
        actual = self.audio_effects.get_config()
        expected = {
            "output": {
                "blocklist": ["Virtual Surround Sink Stream from VirtualSurround"],
                "equalizer#0": {
                    "balance": -2.7755575615628914e-17,
                    "bypass": False,
                    "input-gain": 0.0,
                    "left": {
                        "band0": {
                            "frequency": 120.0,
                            "gain": 0.0,
                            "mode": "BWC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band1": {
                            "frequency": 140.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band2": {
                            "frequency": 200.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band3": {
                            "frequency": 250.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band4": {
                            "frequency": 1000.0,
                            "gain": 3,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band5": {
                            "frequency": 2000.0,
                            "gain": 3,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band6": {
                            "frequency": 5000.0,
                            "gain": 6,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band7": {
                            "frequency": 8000.0,
                            "gain": 12,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                    },
                    "mode": "IIR",
                    "num-bands": 32,
                    "output-gain": 0.0,
                    "pitch-left": 0.0,
                    "pitch-right": 0.0,
                    "right": {
                        "band0": {
                            "frequency": 120.0,
                            "gain": 0.0,
                            "mode": "BWC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band1": {
                            "frequency": 140.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band2": {
                            "frequency": 200.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band3": {
                            "frequency": 250.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band4": {
                            "frequency": 1000.0,
                            "gain": 3,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band5": {
                            "frequency": 2000.0,
                            "gain": 3,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band6": {
                            "frequency": 5000.0,
                            "gain": 6,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band7": {
                            "frequency": 8000.0,
                            "gain": 12,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                    },
                    "split-channels": False,
                },
                "plugins_order": ["equalizer#0"],
            }
        }

        self.assertEqual(actual, expected)

        self.audio_effects.update_treble(-2)
        actual = self.audio_effects.get_config()
        expected = {
            "output": {
                "blocklist": ["Virtual Surround Sink Stream from VirtualSurround"],
                "equalizer#0": {
                    "balance": -2.7755575615628914e-17,
                    "bypass": False,
                    "input-gain": 0.0,
                    "left": {
                        "band0": {
                            "frequency": 120.0,
                            "gain": 0.0,
                            "mode": "BWC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band1": {
                            "frequency": 140.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band2": {
                            "frequency": 200.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band3": {
                            "frequency": 250.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band4": {
                            "frequency": 1000.0,
                            "gain": -1.25,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band5": {
                            "frequency": 2000.0,
                            "gain": -1.25,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band6": {
                            "frequency": 5000.0,
                            "gain": -2.5,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band7": {
                            "frequency": 8000.0,
                            "gain": -6,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                    },
                    "mode": "IIR",
                    "num-bands": 32,
                    "output-gain": 0.0,
                    "pitch-left": 0.0,
                    "pitch-right": 0.0,
                    "right": {
                        "band0": {
                            "frequency": 120.0,
                            "gain": 0.0,
                            "mode": "BWC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band1": {
                            "frequency": 140.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band2": {
                            "frequency": 200.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band3": {
                            "frequency": 250.0,
                            "gain": 0.0,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band4": {
                            "frequency": 1000.0,
                            "gain": -1.25,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band5": {
                            "frequency": 2000.0,
                            "gain": -1.25,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band6": {
                            "frequency": 5000.0,
                            "gain": -2.5,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x1",
                            "solo": False,
                            "type": "Bell",
                        },
                        "band7": {
                            "frequency": 8000.0,
                            "gain": -6,
                            "mode": "RLC (BT)",
                            "mute": False,
                            "q": 4.36,
                            "slope": "x4",
                            "solo": False,
                            "type": "Bell",
                        },
                    },
                    "split-channels": False,
                },
                "plugins_order": ["equalizer#0"],
            }
        }

        self.assertEqual(actual, expected)
